### ISSUE TITLE
More binaries

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal-cache#203]
I built them with my self hosted runners mostly: https://downloads.haskell.org/~ghcup/unofficial-bindists/cabal-cache/1.0.5.4/

* armv7 (might get away with run-on-arch)
* aarch64 (same)
* static linux binaries (the current ones are dynamic, why?)
* Darwin M1 (will need self hosted runner for sure)
* FreeBSD (can use Cirrus CI)

**Comment by newhoggy** [comment]
What setup do you have for building these binaries?

**Comment by newhoggy** [comment]
I would be happy to add you to the organisation if you want to be able to publish releases for `cabal-cache`.

**Comment by hasufell** [comment]
> What setup do you have for building these binaries?

- https://github.com/haskell/ghcup-hs/blob/cabal-cache/.github/scripts/cabal-cache.sh
- https://github.com/haskell/ghcup-hs/blob/cabal-cache/.github/workflows/cabal-cache.yaml

We have self hosted runners for ARM (darwin and linux). The goal is to expose them org-wide for `haskell`. If cabal-cache moves to that org, we could re-use them.

**Comment by newhoggy** [comment]
I'm happy to move the repository to the `haskell` org if that enables publishing more binaries.  What's the process for that and will I be able retain ownership of and admin access to the project?

**Comment by hasufell** [comment]
CCing @Bodigrim

**Comment by newhoggy** [comment]
Just checking back.  Is there still interest in moving this to the `haskell` org?

**Comment by Bodigrim** [comment]
> What's the process for that and will I be able retain ownership of and admin access to the project?

The easiest is if you transfer this repo to me or @hasufell, and we (as admins) transfer it further under github.com/haskell. Yes, you will be able to retain ownership and admin access.

**Comment by Bodigrim** [comment]
> What's the process for that and will I be able retain ownership of and admin access to the project?

The easiest is if you transfer this repo to me or @hasufell, and we (as admins) transfer it further under github.com/haskell. Yes, you will be able to retain ownership and admin access.

**Comment by hasufell** [comment]
@newhoggy if you want to proceed that way, let me know.

**Comment by newhoggy** [comment]
Yep.  That sounds good to me!

**Comment by newhoggy** [comment]
It seems I need to transfer this to my personal account first.  Also, I cannot transfer to you @hasufell because you have a fork of the repository.  Can you delete the fork?

**Comment by hasufell** [comment]
> Yep.  That sounds good to me!

Then please transfer the repository to me.

**Comment by hasufell** [comment]
> It seems I need to transfer this to my personal account first.  Also, I cannot transfer to you @hasufell because you have a fork of the repository.  Can you delete the fork?

Done

**Comment by newhoggy** [comment]
I've initiated the transfer.

**Comment by newhoggy** [comment]
Transfer complete.

**Comment by hasufell** [comment]
https://github.com/haskell/cabal-cache

Regarding CI, here are the tags/runners:
![photo_2024-11-09_12-57-16](https://github.com/user-attachments/assets/0a114d31-3644-4994-9da8-94f64484891a)
